accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.main, name='main'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', views.login, name='login'),
    path('accounts/', views.index, name='index'),
    path('accounts/<int:pk>/', views.detail, name='detail'),
    path('accounts/<int:pk>/update/', views.update, name='update'),
    path('accounts/logout/', views.logout, name='logout'),
    path('accounts/delete/', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    
    @property
    def full_name(self):
        return f'{self.last_name}{self.first_name}'

reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = get_user_model()
        fields = ('username','email', 'password1','password2')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content','movie_name','grade']
        labels = {
            "title": "제목",
            "content": "내용",
            "movie_name": "영화 제목",
            "grade": "평점",
        }

accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def main(request):
    return render(request, 'accounts/main.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:main')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'accounts:main')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def index(request):
    users = get_user_model().objects.all()
    context = {
        'users' : users
    }
    return render(request, 'accounts/index.html', context)

@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user':user,
    }
    return render(request, 'accounts/detail.html', context)

@login_required
def update(request, pk):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form
    }
    return render(request,'accounts/update.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:main')

@login_required
def delete(request):
    request.user.delete()
    auth_logout(request) 
    return redirect('accounts:main')

reviews/views.py
from django.shortcuts import render, redirect
from reviews.models import Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reviews:index')
    else:
        form = ReviewForm()
    context = {
        'form' : form
    }
    return render(request, 'reviews/create.html', context)

def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews
    }
    return render(request, 'reviews/index.html', context)

def detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        'review' : review
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('reviews:detail', review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'reviews/update.html', context)

@login_required
def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect('reviews:index')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">{{user.username}}님의 프로필</h1>
<p>email: {{user.email}}</p>
<p>name: {{user.full_name}}</p>
{% if request.user == user %}
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary">뒤로가기</a>
  <a href="{% url 'accounts:main' %}" class="btn btn-primary">홈으로</a>
  <a href="{% url 'accounts:update' user.pk %}" class="btn btn-success">수정하기</a>
{% else %}
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary">뒤로가기</a>
  <a href="{% url 'accounts:main' %}" class="btn btn-primary">홈으로</a>
{% endif %}
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">User List</h1>
{% for user in users %}
<h3><a class="text-light text-decoration-none" href="{% url 'accounts:detail' user.pk %}">‣ {{user.username}}</a></h3>
{% endfor %}
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type='submit' content='로그인' %}
  <a href="{% url 'accounts:signup' %}" class="btn btn-warning">회원 가입</a>
</form>
</div>
{% endblock %}

accounts/templates/accounts/main.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/1.jpeg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/2.jpeg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/3.jpeg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="container my-5">
  <h1 class="text-center" style="font-size: 3rem;">WELCOME!</h1>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">회원 가입</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="가입하기">
</form>
</div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">수정하기</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="수정 완료">
  <a class="btn btn-outline-danger" href="{%  url 'accounts:delete' %}">회원탈퇴</a>
</form>
</div>
{% endblock %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">리뷰 작성</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="완료">
  <a href="{% url 'reviews:index' %}" class="btn btn-secondary">돌아가기</a>
</form>
</div>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">{{ review.title }}</h1>
  <p>{{ review.content }}</p>
  {% if request.user.is_authenticated %}
    <a href="{% url 'reviews:update' review.pk %}" class="btn btn-primary">수정</a>
    <a href="{% url 'reviews:delete' review.pk  %}" class="btn btn-danger">삭제</a>
    <a href="{% url 'reviews:index' %}" class="btn btn-secondary">뒤로가기</a>
  {% else %}
    <a href="{% url 'reviews:index' %}" class="btn btn-secondary">뒤로가기</a>
  {% endif %}
</div>
{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">Review List</h1>
<table class="table table-dark table-striped table-hover text-center">
  <thead>
    <tr>
      <th scope="col" class="text-center ps-2">영화 제목</th>
      <th scope="col" class="text-center ps-4">리뷰 제목</th>
      <th scope="col" class="text-center ps-4">평점</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <td>
        <a href="{% url 'reviews:detail' review.pk %}" class="text-center text-decoration-none text-white">
          {{ review.title }}
        </a>
      </td>
      <td>
        <p class="text-center text-decoration-none text-white">
          {{ review.movie_name }}
        </p>
      </td>
      <td>
        <p class="text-center text-decoration-none text-white">
          {{ review.grade }}
        </p>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
<h1 class="mb-4">리뷰 수정</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="완료">
  <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-secondary">돌아가기</a>
</form>
</div>
{% endblock %}

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% bootstrap_css %}
</head>

<body class="text-light bg-dark">
  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold" href="{% url 'accounts:main' %}">Review!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <!-- 리뷰 목록 -->
            <a class="nav-link active fw-bold" aria-current="page" href="{% url 'reviews:index' %}">리뷰 목록</a>
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <!-- 리뷰 작성  -->
            <a class="nav-link active fw-bold" href="{% url 'reviews:create' %}">리뷰 작성</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <!-- 리뷰 작성  -->
            <a class="nav-link active fw-bold" href="{% url 'accounts:index' %}">회원 목록</a>
            {% endif %}
          </li>
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active fw-bold" href="{% url 'accounts:detail' user.pk %}">{{ request.user }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active fw-bold" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active fw-bold" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active fw-bold" href="{% url 'accounts:signup' %}">회원 가입</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
    {% block content %}
    {% endblock %}
  {% bootstrap_javascript %}
</body>

</html>